#!/usr/bin/python

import pygame
from pygame.locals import *

pygame.init()
screen = pygame.display.set_mode([50, 50])
pygame.display.update()
while 1:
    event = pygame.event.poll()
    if event.type == QUIT:
        break
    elif event.type == KEYDOWN:
        if event.key == 27:
            break
        print event
    elif event.type == KEYUP:
        print event
    elif event.type != 0:
        print event

    pygame.time.delay(10)
